name: Build debug APK
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  apk:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build debug APK
        run: ./gradlew assembleDebug --warning-mode all --stacktrace
        
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
